import type { RacerId } from '@anywhererace/core';
import { formatDurationS } from '@anywhererace/core';
import type { RaceEvent } from './events';
import { eventsOfType } from './events';
import { buildIncidentTimeline, isRetirement, placesGained } from './results';
import type { FinishRecord, RaceResult } from './types';

/**
 * The race report.
 *
 * Assembled from the event log by template, not written by a model. Three
 * reasons, in order of how much they matter:
 *
 * 1. **A shared race must read identically for everyone.** The whole sharing
 *    model is "share inputs, not recordings" — if the prose were generated by
 *    something non-deterministic, two people opening the same link would get
 *    different accounts of the same race.
 * 2. It has to work offline, like everything else once a track is saved.
 * 3. The event log already carries the facts. Overtakes name both racers and
 *    the position fought over; mistakes carry their cause and cost; laps carry
 *    personal and race bests. There is nothing to invent.
 *
 * The writing aims for a race report rather than commentary: what decided it,
 * who moved, what went wrong. Every beat is dropped when it does not apply, so
 * a processional race produces two sentences rather than padding.
 */

export type NarrativeBeat = {
  /** Machine-readable, so the UI can style or filter beats. */
  kind: 'headline' | 'start' | 'decisive' | 'mover' | 'incident' | 'attrition' | 'fastest';
  text: string;
};

export type RaceNarrative = {
  headline: string;
  beats: NarrativeBeat[];
  /** The whole thing as plain text, for sharing and for OG images. */
  text: string;
};

export type NarrativeInput = {
  result: RaceResult;
  events: readonly RaceEvent[];
  /** Display names by racer id. Ids alone would make unreadable prose. */
  names: ReadonlyMap<RacerId, string>;
  trackName?: string;
};

/** A win by less than this is "a photo finish" rather than a margin. */
const PHOTO_FINISH_S = 0.5;
/** Above this, the winner was never really challenged. */
const COMFORTABLE_WIN_S = 20;
/** Places gained before a climb through the field is worth remarking on. */
const NOTABLE_CLIMB = 3;
/** Time lost in one moment before it counts as the incident of the race. */
const NOTABLE_TIME_LOSS_S = 3;

export const buildNarrative = (input: NarrativeInput): RaceNarrative => {
  const { result, events, names } = input;
  const name = (id: RacerId): string => names.get(id) ?? id;

  const classified = result.finishers.slice().sort((a, b) => a.position - b.position);
  const winner = classified[0];
  const grid = eventsOfType(events, 'race-start')[0]?.grid ?? [];

  if (winner === undefined) {
    return { headline: 'Nobody finished.', beats: [], text: 'Nobody finished.' };
  }

  const beats: NarrativeBeat[] = [];
  const headline = buildHeadline(winner, classified, name, input.trackName);
  beats.push({ kind: 'headline', text: headline });

  const start = buildStart(winner, grid, name);
  if (start !== undefined) beats.push({ kind: 'start', text: start });

  const decisive = buildDecisive(events, winner, name);
  if (decisive !== undefined) beats.push({ kind: 'decisive', text: decisive });

  const mover = buildMover(classified, grid, name);
  if (mover !== undefined) beats.push({ kind: 'mover', text: mover });

  const incident = buildIncident(events, name);
  if (incident !== undefined) beats.push({ kind: 'incident', text: incident });

  const fastest = buildFastest(events, name);
  if (fastest !== undefined) beats.push({ kind: 'fastest', text: fastest });

  const attrition = buildAttrition(classified, name);
  if (attrition !== undefined) beats.push({ kind: 'attrition', text: attrition });

  return { headline, beats, text: beats.map((beat) => beat.text).join(' ') };
};

const buildHeadline = (
  winner: FinishRecord,
  classified: readonly FinishRecord[],
  name: (id: RacerId) => string,
  trackName: string | undefined,
): string => {
  const where = trackName === undefined ? '' : ` at ${trackName}`;
  const runnerUp = classified[1];

  if (winner.status !== 'finished') {
    return `Nobody saw the flag${where}. ${name(winner.racerId)} got furthest.`;
  }
  if (runnerUp === undefined || runnerUp.gapToWinnerS === undefined) {
    return `${name(winner.racerId)} won${where} unopposed.`;
  }

  const margin = runnerUp.gapToWinnerS;
  if (margin < PHOTO_FINISH_S) {
    return `${name(winner.racerId)} won${where} by ${margin.toFixed(2)}s — a photo finish from ${name(runnerUp.racerId)}.`;
  }
  if (margin > COMFORTABLE_WIN_S) {
    return `${name(winner.racerId)} won${where} as they liked, ${formatDurationS(margin, 1)} clear of ${name(runnerUp.racerId)}.`;
  }
  return `${name(winner.racerId)} won${where} by ${margin.toFixed(2)}s from ${name(runnerUp.racerId)}.`;
};

const buildStart = (
  winner: FinishRecord,
  grid: readonly RacerId[],
  name: (id: RacerId) => string,
): string | undefined => {
  const poleSitter = grid[0];
  if (poleSitter === undefined) return undefined;
  if (poleSitter === winner.racerId) return `They led away from pole and were never headed.`;

  const gridSlot = grid.indexOf(winner.racerId);
  if (gridSlot < 0) return `${name(poleSitter)} led away from pole.`;
  return `${name(poleSitter)} led away from pole; the winner started ${gridSlot + 1}th.`;
};

/**
 * The last time the lead changed hands — which is, almost always, the moment
 * the race was decided.
 */
const buildDecisive = (
  events: readonly RaceEvent[],
  winner: FinishRecord,
  name: (id: RacerId) => string,
): string | undefined => {
  const forTheLead = eventsOfType(events, 'overtake').filter((event) => event.forPosition === 1);
  const last = forTheLead[forTheLead.length - 1];
  if (last === undefined) return undefined;

  const changes = forTheLead.length;
  const when = `on the ${ordinal(Math.max(1, Math.round(last.atS / 60)))} minute`;

  if (last.racerId === winner.racerId) {
    return changes === 1
      ? `The lead changed once, when they took it from ${name(last.victimId)} ${when}.`
      : `The lead changed ${changes} times; the one that stuck came ${when}, past ${name(last.victimId)}.`;
  }
  // The last pass for the lead was not by the eventual winner, so whoever made
  // it lost the lead again some other way — a retirement, or being repassed
  // without the pair swapping again inside the cooldown.
  return `The lead changed ${changes} times, the last of them ${when} when ${name(last.racerId)} went by ${name(last.victimId)}.`;
};

const buildMover = (
  classified: readonly FinishRecord[],
  grid: readonly RacerId[],
  name: (id: RacerId) => string,
): string | undefined => {
  if (grid.length === 0) return undefined;

  let best: { finisher: FinishRecord; gained: number } | undefined;
  for (const finisher of classified) {
    if (isRetirement(finisher.status)) continue;
    const gained = placesGained(finisher, grid);
    if (gained === undefined || gained < NOTABLE_CLIMB) continue;
    if (best === undefined || gained > best.gained) best = { finisher, gained };
  }
  if (best === undefined) return undefined;

  const gridSlot = grid.indexOf(best.finisher.racerId) + 1;
  return `${name(best.finisher.racerId)} climbed ${best.gained} places, ${ordinal(gridSlot)} to ${ordinal(best.finisher.position)}.`;
};

const buildIncident = (
  events: readonly RaceEvent[],
  name: (id: RacerId) => string,
): string | undefined => {
  const incidents = buildIncidentTimeline(events);

  // A retirement outranks any amount of time lost: it ended someone's race.
  const retirement = incidents.find((incident) => incident.terminal);
  if (retirement !== undefined) {
    const lap = retirement.lap === undefined ? '' : ` on lap ${retirement.lap + 1}`;
    return retirement.kind === 'crash'
      ? `${name(retirement.racerId)} put it in the scenery${lap}.`
      : `${name(retirement.racerId)} stopped${lap} with a mechanical.`;
  }

  const worst = incidents
    .filter((incident) => (incident.timeLostS ?? 0) >= NOTABLE_TIME_LOSS_S)
    .sort((a, b) => (b.timeLostS ?? 0) - (a.timeLostS ?? 0))[0];
  if (worst === undefined) return undefined;

  const cause = worst.fromPassAttempt ? ' trying a move that was not there' : '';
  return `The costliest moment was ${name(worst.racerId)}${cause} — ${worst.timeLostS?.toFixed(1)}s gone in one go.`;
};

const buildFastest = (
  events: readonly RaceEvent[],
  name: (id: RacerId) => string,
): string | undefined => {
  const raceBests = eventsOfType(events, 'lap').filter((event) => event.raceBest);
  const fastest = raceBests[raceBests.length - 1];
  if (fastest === undefined) return undefined;
  return `Fastest lap went to ${name(fastest.racerId)}, ${formatDurationS(fastest.lapTimeS, 2)} on lap ${fastest.lap}.`;
};

const buildAttrition = (
  classified: readonly FinishRecord[],
  name: (id: RacerId) => string,
): string | undefined => {
  const retired = classified.filter((finisher) => isRetirement(finisher.status));
  if (retired.length === 0) return `All ${classified.length} finished.`;
  if (retired.length === 1) {
    const only = retired[0];
    return only === undefined ? undefined : `${name(only.racerId)} was the only retirement.`;
  }
  return `${retired.length} of ${classified.length} failed to finish.`;
};

const ordinal = (value: number): string => {
  const remainderTen = value % 10;
  const remainderHundred = value % 100;
  if (remainderTen === 1 && remainderHundred !== 11) return `${value}st`;
  if (remainderTen === 2 && remainderHundred !== 12) return `${value}nd`;
  if (remainderTen === 3 && remainderHundred !== 13) return `${value}rd`;
  return `${value}th`;
};
